# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isFavorite',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='song',
            name='songTitle',
            field=models.CharField(max_length=15),
        ),
    ]
