# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170930_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
